# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. 

createCohortDiagnosticsModuleSpecifications <- function(runInclusionStatistics = TRUE,
                                                        runIncludedSourceConcepts = TRUE,
                                                        runOrphanConcepts = TRUE,
                                                        runTimeSeries = FALSE,
                                                        runVisitContext = TRUE,
                                                        runBreakdownIndexEvents = TRUE,
                                                        runIncidenceRate = TRUE,
                                                        runCohortRelationship = TRUE,
                                                        runTemporalCohortCharacterization = TRUE,
                                                        temporalCovariateSettings = FeatureExtraction::createTemporalCovariateSettings(useDemographicsGender = TRUE,     useDemographicsAge = TRUE, useDemographicsAgeGroup = TRUE,     useDemographicsRace = TRUE, useDemographicsEthnicity = TRUE,     useDemographicsIndexYear = TRUE, useDemographicsIndexMonth = TRUE,     useDemographicsIndexYearMonth = TRUE, useDemographicsPriorObservationTime = TRUE,     useDemographicsPostObservationTime = TRUE, useDemographicsTimeInCohort = TRUE,     useConditionOccurrence = TRUE, useProcedureOccurrence = TRUE,     useDrugEraStart = TRUE, useMeasurement = TRUE, useConditionEraStart = TRUE,     useConditionEraOverlap = TRUE, useConditionEraGroupStart = FALSE,     useConditionEraGroupOverlap = TRUE, useDrugExposure = FALSE,     useDrugEraOverlap = FALSE, useDrugEraGroupStart = FALSE,     useDrugEraGroupOverlap = TRUE, useObservation = TRUE, useDeviceExposure = TRUE,     useCharlsonIndex = TRUE, useDcsi = TRUE, useChads2 = TRUE,     useChads2Vasc = TRUE, useHfrs = FALSE, temporalStartDays = c(-9999,         -365, -180, -30, -365, -30, 0, 1, 31, -9999), temporalEndDays = c(0,         0, 0, 0, -31, -1, 0, 30, 365, 9999)),
                                                        incremental = FALSE) {
  analysis <- list()
  for (name in names(formals(createCohortDiagnosticsModuleSpecifications))) {
    analysis[[name]] <- get(name)
  }

  specifications <- list(module = "CohortDiagnosticsModule",
                         version = "0.0.1",
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi",
                         settings = analysis)
  class(specifications) <- c("CohortDiagnosticsModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}
